version: "3.8"
services: 
  server:
    # https://hub.docker.com/_/nginx
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile 
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80" 
    depends_on: 
      - php
      - mysql  
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    # bind mount to laravel sorce code
    volumes: 
      # :delegated if the container should write data it is not instatly reflected back to the host machine - for better performance, :ro is not an option
      - ./src:/var/www/html:delegated
      - ./src:/var/www/html/storage/logs
      - ./src:/var/www/html/storage/framework/sessions
      - ./src:/var/www/html/storage/framework/views
      - ./src:/var/www/html/storage/framework/cache
    # port define in nginx.conf 3000 default port php image expose 9000 but we have direct container to container comm so change port in nginx.conf from 3000 to 9000
    # ports: 
    #   - '3000:9000'
  #https://hub.docker.com/_/mysql  
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env 
  #laravel     
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html
  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - ./src:/var/www/html
    # override dockerfile run
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: alpine/node
    working_dir: /var/www/html 
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html